#!/bin/sh
### BEGIN INIT INFO
# Provides:          test
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       test
### END INIT INFO

SCRIPT=/etc/init.d/test
RUNAS=ubuntu

PIDFILE=/var/run/test.pid
LOGFILE=/tmp/test.log

start() {
  if [ -f /tmp/test.log ]
  then 
   touch /tmp/test.log
  fi 
 
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  if [ ! -d /var/run/test ]
then
  install -m 0755 -o ubuntu -d /var/run/test
else
  chown ubuntu:ubuntu /var/run/test
  chmod 0755 /var/run/test
fi 
  #curl -sSL https://get.docker.com/ | sh
  #sudo groupadd docker
  #sudo gpasswd -a $USER docker
  #newgrp docker
  #sudo usermod -aG docker ubuntu

  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f test remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
